# cast-client-channels.ini - TelliCast+TelliVision Client channel 
# configuration file
#
# 14/04/2024
#
[config_version]
# This section is needed for automatic version updates.
# Do not remove or edit by hand!

# Comments starting with double hashes will be preserved in case of version
# updates.
#   e.g.: ##This is a comment which will be preserved.
version=2.14
# version: The version of the configuration file
#          MANDATORY parameter! 
# ------------------

# [channel]
# name=E1B-Charter-1
# target_directory=\EUMETCast\received\bas\E1B-Charter-1
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-DCP-1
# target_directory=\EUMETCast\received\bas\E1B-DCP-1
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-DWDSAT
# target_directory=\EUMETCast\received\bas\E1B-DWDSAT
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-1
# target_directory=\EUMETCast\received\bas\E1B-EPS-1
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-10
# target_directory=\EUMETCast\received\bas\E1B-EPS-10
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-11
# target_directory=\EUMETCast\received\bas\E1B-EPS-11
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-2
# target_directory=\EUMETCast\received\bas\E1B-EPS-2
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-3
# target_directory=\EUMETCast\received\bas\E1B-EPS-3
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-5
# target_directory=\EUMETCast\received\bas\E1B-EPS-5
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-6
# target_directory=\EUMETCast\received\bas\E1B-EPS-6
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-7
# target_directory=\EUMETCast\received\bas\E1B-EPS-7
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-8
# target_directory=\EUMETCast\received\bas\E1B-EPS-8
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-N-13
# target_directory=\EUMETCast\received\bas\E1B-EPS-N-13
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-N-14
# target_directory=\EUMETCast\received\bas\E1B-EPS-N-14
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-N-15
# target_directory=\EUMETCast\received\bas\E1B-EPS-N-15
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-N-16
# target_directory=\EUMETCast\received\bas\E1B-EPS-N-16
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-EPS-N-17
# target_directory=\EUMETCast\received\bas\E1B-EPS-N-17
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-GEO-1
# target_directory=\EUMETCast\received\bas\E1B-GEO-1
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-GEO-2
# target_directory=\EUMETCast\received\bas\E1B-GEO-2
# tmp_directory=\EUMETCast\tmp\bas

[channel]
name=E1B-GEO-3
target_directory=\EUMETCast\received\bas\E1B-GEO-3
tmp_directory=\EUMETCast\tmp\bas

[channel]
name=E1B-GEO-4
target_directory=\EUMETCast\received\bas\E1B-GEO-4
tmp_directory=\EUMETCast\tmp\bas

[channel]
name=E1B-GEO-5
target_directory=\EUMETCast\received\bas\E1B-GEO-5
tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-GEO-6
# target_directory=\EUMETCast\received\bas\E1B-GEO-6
# tmp_directory=\EUMETCast\tmp\bas

[channel]
name=E1B-Info-Channel-1
target_directory=\EUMETCast\received\bas\E1B-Info-Channel-1
tmp_directory=\EUMETCast\tmp\bas

[channel]
name=E1B-Info-Channel-2
target_directory=\EUMETCast\received\bas\E1B-Info-Channel-2
tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-JAS-3
# target_directory=\EUMETCast\received\bas\E1B-JAS-3
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-MSG-PAR
# target_directory=\EUMETCast\received\bas\E1B-MSG-PAR
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-RDS-1
# target_directory=\EUMETCast\received\bas\E1B-RDS-1
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-RDS-2
# target_directory=\EUMETCast\received\bas\E1B-RDS-2
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-SAF-1
# target_directory=\EUMETCast\received\bas\E1B-SAF-1
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-SAF-2
# target_directory=\EUMETCast\received\bas\E1B-SAF-2
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-SAF-3
# target_directory=\EUMETCast\received\bas\E1B-SAF-3
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-SAF-4
# target_directory=\EUMETCast\received\bas\E1B-SAF-4
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-SAF-5
# target_directory=\EUMETCast\received\bas\E1B-SAF-5
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-SAF-6
# target_directory=\EUMETCast\received\bas\E1B-SAF-6
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-SRL
# target_directory=\EUMETCast\received\bas\E1B-SRL
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-TPC-1
# target_directory=\EUMETCast\received\bas\E1B-TPC-1
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-TPC-3
# target_directory=\EUMETCast\received\bas\E1B-TPC-3
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-TPC-5
# target_directory=\EUMETCast\received\bas\E1B-TPC-5
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-TPC-6
# target_directory=\EUMETCast\received\bas\E1B-TPC-6
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-TPG-1
# target_directory=\EUMETCast\received\bas\E1B-TPG-1
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-TPL-1
# target_directory=\EUMETCast\received\bas\E1B-TPL-1
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-TRN
# target_directory=\EUMETCast\received\bas\E1B-TRN
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-WMO-RA-I
# target_directory=\EUMETCast\received\bas\E1B-WMO-RA-I
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=E1B-WMO-RA-VI
# target_directory=\EUMETCast\received\bas\E1B-WMO-RA-VI
# tmp_directory=\EUMETCast\tmp\bas

# [channel]
# name=*
# target_directory=\EUMETCast\received\bas\default
# tmp_directory=\EUMETCast\tmp\bas

# DO NOT EDIT OR DELETE THE FOLLOWING SECTION!!!
[channel]
name=WWW-Channel
target_directory=www/eumetsat
tmp_directory=www/tmp

